import {useEffect,useMemo,useState} from 'react';
import {applyPlan,captureSnapshot,createDantePlan,createVLANPlan,getConfigStatus,getDanteHealth,getSnapshots,getTopology,rollbackSnapshot,scan,trustHostKey} from './api';
import type {ConfigPlan,ConfigStatus,DanteHealth,Port,Snapshot,Switch,Topology} from './types';

type View='topology'|'switches'|'traffic'|'vlans'|'dante'|'snapshots';
const roles:Record<string,string>={Dante:'#9168ff',Control:'#23a7ff',Lighting:'#f0aa34',Video:'#ed5d86',Access:'#2ed47a',Trunk:'#23a7ff',Unused:'#66717e',Unassigned:'#2ed47a'};
const nav:{id:View;icon:string;label:string}[]=[
  {id:'topology',icon:'⌘',label:'Topologie'},
  {id:'switches',icon:'▦',label:'Switches'},
  {id:'traffic',icon:'◉',label:'Live Traffic'},
  {id:'vlans',icon:'◇',label:'VLANs & Rollen'},
  {id:'dante',icon:'♪',label:'Dante-Zustand'},
  {id:'snapshots',icon:'↶',label:'Snapshots'},
];

export function App(){
  const[data,setData]=useState<Topology|null>(null),[selected,setSelected]=useState(''),[view,setView]=useState<View>('topology'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[snapshots,setSnapshots]=useState<Snapshot[]>([]);
  async function load(){try{const v=await getTopology();setData(v);setSelected(id=>id||v.switches[0]?.id||'');setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}}
  useEffect(()=>{let stopped=false,timer=0;const poll=async()=>{await load();if(!stopped)timer=window.setTimeout(poll,3000)};void poll();return()=>{stopped=true;clearTimeout(timer)}},[]);
  useEffect(()=>{if(view==='snapshots')void getSnapshots(selected).then(setSnapshots).catch(e=>setError(e instanceof Error?e.message:String(e)))},[view,selected]);
  const sw=useMemo(()=>data?.switches.find(s=>s.id===selected)??data?.switches[0],[data,selected]);
  async function discover(){setBusy(true);try{await scan();await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  const activePorts=data?.switches.flatMap(s=>s.ports.filter(p=>p.link).map(p=>({sw:s,port:p})))??[];
  return <div className="shell">
    <header><div className="brand"><span className="pulse"/><div><b>Event Network Manager</b><small>Production Network · {data?.source??'verbinde …'}</small></div></div><div className="summary"><Metric value={data?.switches.length??'–'} label="Switches"/><Metric value={activePorts.length||'–'} label="aktive Ports"/><Metric value="LOCAL" label="Modus" good/></div><button onClick={discover} disabled={busy}>{busy?'Scannt …':'Netzwerk scannen'}</button></header>
    <div className="layout"><aside><nav>{nav.map(item=><button key={item.id} className={view===item.id?'active':''} onClick={()=>setView(item.id)}><span>{item.icon}</span>{item.label}</button>)}</nav><div className="legend"><b>Port-Rollen</b>{Object.entries(roles).slice(0,7).map(([r,c])=><span key={r}><i style={{background:c}}/>{r}</span>)}</div></aside>
    <main><ViewTitle view={view} updatedAt={data?.updatedAt}/>{error&&<div className="error">{error}. Das Backend ist nicht erreichbar.</div>}
      {view==='topology'&&<TopologyView data={data} selected={selected} onSelect={setSelected}/>}
      {view==='switches'&&<SwitchesView data={data} selected={selected} onSelect={setSelected}/>}
      {view==='traffic'&&<TrafficView rows={activePorts}/>}
      {view==='vlans'&&<VLANView data={data} selected={selected} onApplied={load}/>}
      {view==='dante'&&<DanteView data={data} selected={selected} onApplied={load}/>}
      {view==='snapshots'&&<SnapshotsView snapshots={snapshots} switchId={selected} onRefresh={()=>getSnapshots(selected).then(setSnapshots)}/>}
    </main><Inspector sw={sw} onEditVLANs={()=>setView('vlans')}/></div>
  </div>
}

function Metric({value,label,good}:{value:string|number;label:string;good?:boolean}){return <div className="metric"><b className={good?'good':''}>{value}</b><small>{label}</small></div>}
function ViewTitle({view,updatedAt}:{view:View;updatedAt?:string}){const titles:Record<View,[string,string]>={topology:['Netzwerk-Topologie','LLDP/CDP-Ansicht'],switches:['Switches','Inventar und Gerätezustand'],traffic:['Live Traffic','RX/TX und Interfacefehler'],vlans:['VLANs & Rollen','Portmitgliedschaften und PVID'],dante:['Dante-Zustand','Bereitschaft von QoS, IGMP und EEE'],snapshots:['Config-Snapshots','Lokale Wiederherstellungspunkte']};return <div className="title"><div><h1>{titles[view][0]}</h1><p>{titles[view][1]} · automatisch aktualisiert</p></div><span className="live">● {updatedAt?new Date(updatedAt).toLocaleTimeString('de-DE'):'LIVE'}</span></div>}
function TopologyView({data,selected,onSelect}:{data:Topology|null;selected:string;onSelect:(id:string)=>void}){if(!data)return <Loading/>;return <div className="topology"><svg className="links" viewBox="0 0 800 430" preserveAspectRatio="none">{data.links.map((link,i)=><path key={link.id} d={i%2===0?'M400 135 L210 295':'M400 135 L590 295'}/>)}</svg>{data.switches.map((s,i)=><button key={s.id} className={`node n${Math.min(i,2)} ${selected===s.id?'selected':''}`} onClick={()=>onSelect(s.id)}><span className={`state ${s.status}`}/><div><b>{s.name}</b><small>{s.model} · {s.address}</small></div><PortMini sw={s}/></button>)}</div>}
function PortMini({sw}:{sw:Switch}){return <div className="miniports">{sw.ports.map(p=><i key={p.index} className={p.link?'up':''} style={p.link?{background:roles[p.role]??roles.Unassigned}:{}} title={`${p.name} · ${p.role}`}/>)}</div>}
function SwitchesView({data,selected,onSelect}:{data:Topology|null;selected:string;onSelect:(id:string)=>void}){if(!data)return <Loading/>;return <div className="cards">{data.switches.map(s=><button className={`device-card ${s.id===selected?'selected':''}`} onClick={()=>onSelect(s.id)} key={s.id}><span className={`state ${s.status}`}/><h2>{s.name}</h2><p>{s.model}</p><dl><dt>Adresse</dt><dd>{s.address}</dd><dt>Firmware</dt><dd>{s.firmwareVersion||'–'}</dd><dt>Seriennummer</dt><dd>{s.serialNumber||'–'}</dd><dt>MAC</dt><dd>{s.macAddress||'–'}</dd><dt>Ports online</dt><dd>{s.ports.filter(p=>p.link).length} / {s.ports.length}</dd></dl></button>)}</div>}
function TrafficView({rows}:{rows:{sw:Switch;port:Port}[]}){return <DataPanel><table><thead><tr><th>Switch</th><th>Port</th><th>Rolle</th><th>Speed</th><th>RX Mbit/s</th><th>TX Mbit/s</th><th>Fehler</th><th>PoE</th></tr></thead><tbody>{rows.length?rows.map(({sw,port})=><tr key={`${sw.id}-${port.index}`}><td>{sw.name}</td><td>{port.name}</td><td><Role role={port.role}/></td><td>{port.speedMbps||'–'} M</td><td className="number">{port.rxMbps.toFixed(3)}</td><td className="number">{port.txMbps.toFixed(3)}</td><td className={port.errors?'warn number':'number'}>{port.errors}</td><td>{port.poeWatts?`${port.poeWatts.toFixed(1)} W`:'–'}</td></tr>):<Empty text="Keine aktiven Ports"/>}</tbody></table></DataPanel>}
function VLANView({data,selected,onApplied}:{data:Topology|null;selected:string;onApplied:()=>Promise<void>}){
  const[ports,setPorts]=useState<number[]>([]),[vlan,setVlan]=useState(1),[mode,setMode]=useState<'access'|'trunk'>('access'),[plan,setPlan]=useState<ConfigPlan|null>(null),[status,setStatus]=useState<ConfigStatus|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const sw=data?.switches.find(s=>s.id===selected)??data?.switches[0];
  useEffect(()=>{if(sw){setPorts([]);setPlan(null);setVlan(data?.vlans[0]?.id??1);void getConfigStatus(sw.id).then(setStatus).catch(e=>setMessage(e.message))}},[sw?.id]);
  if(!data||!sw)return <Loading/>;
  const toggle=(port:number)=>{setPlan(null);setPorts(current=>current.includes(port)?current.filter(v=>v!==port):[...current,port].sort((a,b)=>a-b))};
  const preview=async()=>{setBusy(true);try{setPlan(await createVLANPlan(sw.id,vlan,ports,mode));setMessage('Änderungsplan ist bereit. Bitte Befehle und Hinweise prüfen.')}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  const apply=async()=>{if(!plan||!window.confirm(`${plan.description}\n\nVorher wird automatisch ein vollständiger Snapshot angelegt. Änderung jetzt ausführen?`))return;setBusy(true);try{const snapshot=await applyPlan(plan);setMessage(`VLAN-Zuweisung angewendet. Sicherungs-Snapshot: ${snapshot.id}`);setPlan(null);await onApplied()}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  const trust=async()=>{if(!status?.hostKeyFingerprint||!window.confirm(`SSH-Hostschlüssel wirklich vertrauen?\n\n${status.hostKeyFingerprint}`))return;setBusy(true);try{setStatus(await trustHostKey(sw.id,status.hostKeyFingerprint));setMessage('SSH-Hostschlüssel bestätigt.')}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  const risky=sw.ports.filter(p=>ports.includes(p.index)&&(p.link||p.vlanMode==='trunk'));
  return <div className="stack"><section className="vlan-editor"><div><h2>{sw.name}: Ports einem VLAN zuweisen</h2><p>Ports auswählen, Ziel-VLAN und Zuweisungsart festlegen. Vor jeder Änderung zeigt die App einen prüfbaren Plan.</p></div><div className="editor-fields"><label>Ziel-VLAN<select value={vlan} onChange={e=>{setVlan(Number(e.target.value));setPlan(null)}}>{data.vlans.map(v=><option key={v.id} value={v.id}>VLAN {v.id}{v.name?` · ${v.name}`:''}</option>)}</select></label><label>Zuweisungsart<select value={mode} onChange={e=>{setMode(e.target.value as 'access'|'trunk');setPlan(null)}}><option value="access">Access · ungetaggt</option><option value="trunk">Trunk · getaggt hinzufügen</option></select></label></div><div className="config-actions"><button onClick={preview} disabled={busy||!ports.length}>Änderungsplan prüfen</button><button className="danger" onClick={apply} disabled={busy||!plan||!status?.available}>Snapshot erstellen und anwenden</button></div>{!status?.hostKeyTrusted&&status?.hostKeyFingerprint&&<div className="inline-notice"><span>Für Änderungen muss der SSH-Hostschlüssel bestätigt sein.</span><button onClick={trust} disabled={busy}>Hostschlüssel bestätigen</button></div>}{risky.length>0&&<p className="message">Hinweis: {risky.length} gewählte Ports haben Link oder sind bereits Trunks. Uplink-Verbindungen vor dem Anwenden prüfen.</p>}{message&&<p className="message">{message}</p>}{plan&&<div className="plan"><b>{plan.description}</b>{plan.warnings.map(w=><p key={w}>⚠ {w}</p>)}<pre>{plan.commands.join('\n')}</pre></div>}</section><div className="chips">{data.vlans.map(v=><span key={v.id}>VLAN {v.id}{v.name&&v.name!==String(v.id)?` · ${v.name}`:''}</span>)}</div><DataPanel><table className="select-table"><thead><tr><th><input type="checkbox" aria-label="Alle Ports auswählen" checked={ports.length===sw.ports.length} onChange={e=>{setPlan(null);setPorts(e.target.checked?sw.ports.map(p=>p.index):[])}}/></th><th>Port</th><th>Status</th><th>Modus</th><th>PVID</th><th>Ungetaggt</th><th>Getaggt</th><th>Rolle</th></tr></thead><tbody>{sw.ports.map(p=><tr key={p.index} className={ports.includes(p.index)?'row-selected':''} onClick={()=>toggle(p.index)}><td><input type="checkbox" aria-label={`${p.name} auswählen`} checked={ports.includes(p.index)} onChange={()=>toggle(p.index)} onClick={e=>e.stopPropagation()}/></td><td>{p.name}</td><td><span className={p.link?'good':''}>{p.link?'Link':'Down'}</span></td><td>{p.vlanMode||'–'}</td><td>{p.pvid||'–'}</td><td>{p.untaggedVlans.join(', ')||'–'}</td><td>{p.taggedVlans.join(', ')||'–'}</td><td><Role role={p.role}/></td></tr>)}</tbody></table></DataPanel></div>
}
function DanteView({data,selected,onApplied}:{data:Topology|null;selected:string;onApplied:()=>Promise<void>}){
  const[status,setStatus]=useState<ConfigStatus|null>(null),[plan,setPlan]=useState<ConfigPlan|null>(null),[health,setHealth]=useState<DanteHealth|null>(null),[ports,setPorts]=useState<number[]>([]),[vlan,setVlan]=useState(1),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const sw=data?.switches.find(s=>s.id===selected)??data?.switches[0];
  useEffect(()=>{if(sw){const linked=sw.ports.filter(p=>p.index<=24&&p.link).map(p=>p.index);setPorts(linked.length?linked:(sw.ports.some(p=>p.index===1)?[1]:[]));setVlan(data?.vlans[0]?.id??1);void getConfigStatus(sw.id).then(setStatus).catch(e=>setMessage(e.message))}},[sw?.id]);
  if(!data||!sw)return <Loading/>;
  const toggle=(port:number)=>{setHealth(null);setPlan(null);setPorts(current=>current.includes(port)?current.filter(v=>v!==port):[...current,port].sort((a,b)=>a-b))};
  const trust=async()=>{if(!status?.hostKeyFingerprint||!window.confirm(`SSH-Hostschlüssel wirklich vertrauen?\n\n${status.hostKeyFingerprint}`))return;setBusy(true);try{setStatus(await trustHostKey(sw.id,status.hostKeyFingerprint));setMessage('Hostschlüssel bestätigt.')}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  const check=async()=>{setBusy(true);try{const result=await getDanteHealth(sw.id,vlan,ports);setHealth(result);setMessage(result.messages.join(' '))}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  const preview=async()=>{setBusy(true);try{setPlan(await createDantePlan(sw.id,vlan,ports));setMessage('Konfigurationsplan ist bereit.')}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  const apply=async()=>{if(!plan||!window.confirm('Dante-Konfiguration anwenden? Vorher wird automatisch ein vollständiger Snapshot angelegt.'))return;setBusy(true);try{const snapshot=await applyPlan(plan);setMessage(`Dante-Konfiguration angewendet. Sicherungs-Snapshot: ${snapshot.id}`);setPlan(null);await onApplied();setHealth(await getDanteHealth(sw.id,vlan,ports))}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  return <div className="health-grid"><Health title="IGMP Snooping" ok={!!health?.igmpGlobal&&!!health?.igmpVlan} text={health?`${health.igmpGlobal&&health.igmpVlan?'Aktiv':'Unvollständig'} für VLAN ${vlan}`:'Noch nicht geprüft'}/><Health title="SSH-Verbindung" ok={!!status?.available} text={status?.message??'wird geprüft …'}/><Health title="DSCP-Priorisierung" ok={!!health?.qosDscp&&health.qosTrustedPorts===health.selectedPorts} text={health?`${health.qosTrustedPorts}/${health.selectedPorts} Ports vertrauen QoS-Markierungen`:'Noch nicht geprüft'}/><Health title="Energiesparmodus (EEE)" ok={!!health&&health.eeeDisabledPorts===health.selectedPorts} text={health?`Auf ${health.eeeDisabledPorts}/${health.selectedPorts} Dante-Ports deaktiviert`:'Noch nicht geprüft'}/>
    {!status?.hostKeyTrusted&&status?.hostKeyFingerprint&&<section className="notice"><b>SSH-Hostschlüssel bestätigen</b><p><code>{status.hostKeyAlgorithm} {status.hostKeyFingerprint}</code></p><button onClick={trust} disabled={busy}>Diesen Schlüssel vertrauen</button></section>}
    <section className="configurator"><div className="config-row"><label>Dante-VLAN<select value={vlan} onChange={e=>{setVlan(Number(e.target.value));setHealth(null);setPlan(null)}}>{data.vlans.map(v=><option value={v.id} key={v.id}>VLAN {v.id}</option>)}</select></label><div><b>Dante-Ports</b><div className="port-picker">{sw.ports.filter(p=>p.index<=24).map(p=><button className={ports.includes(p.index)?'selected':''} onClick={()=>toggle(p.index)} key={p.index}>{p.index}</button>)}</div></div></div><div className="config-actions"><button onClick={check} disabled={busy||!ports.length||!status?.available}>Aktuellen Zustand prüfen</button><button onClick={preview} disabled={busy||!ports.length}>Konfigurationsplan prüfen</button><button className="danger" onClick={apply} disabled={busy||!plan||!status?.available}>Snapshot erstellen und anwenden</button></div>{message&&<p className="message">{message}</p>}{health&&<p className={health.healthy?'health-success':'message'}>Prüfung: {health.healthy?'Dante-Konfiguration vollständig aktiv.':'Handlungsbedarf erkannt.'}</p>}{plan&&<div className="plan"><b>{plan.description}</b>{plan.warnings.map(w=><p key={w}>⚠ {w}</p>)}<pre>{plan.commands.join('\n')}</pre></div>}</section>
  </div>
}
function SnapshotsView({snapshots,switchId,onRefresh}:{snapshots:Snapshot[];switchId:string;onRefresh:()=>void}){const[busy,setBusy]=useState(false),[message,setMessage]=useState('');const capture=async()=>{setBusy(true);try{const s=await captureSnapshot(switchId);setMessage(`Snapshot ${s.id} erstellt.`);onRefresh()}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};const rollback=async(id:string)=>{if(!window.confirm('Diesen Snapshot-Rollback anwenden? Der Switch wird danach erneut geprüft.'))return;setBusy(true);try{await rollbackSnapshot(id);setMessage('Rollback erfolgreich angewendet.')}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};return <div className="stack"><div className="toolbar"><button onClick={capture} disabled={busy||!switchId}>Jetzt Snapshot erstellen</button>{message&&<span>{message}</span>}</div><DataPanel>{snapshots.length?<table><thead><tr><th>Zeitpunkt</th><th>Switch</th><th>Snapshot-ID</th><th>Größe</th><th></th></tr></thead><tbody>{snapshots.map(s=><tr key={s.id}><td>{new Date(s.createdAt).toLocaleString('de-DE')}</td><td>{s.switchId}</td><td><code>{s.id}</code></td><td>{s.sizeBytes} Bytes</td><td><button className="table-action" onClick={()=>rollback(s.id)} disabled={busy}>Rollback</button></td></tr>)}</tbody></table>:<div className="empty-state"><b>Noch keine Snapshots</b><p>Vor der ersten Konfigurationsänderung wird automatisch ein vollständiger Snapshot angelegt.</p></div>}</DataPanel></div>}
function Inspector({sw,onEditVLANs}:{sw?:Switch;onEditVLANs:()=>void}){if(!sw)return <section className="inspector"/>;const rx=sw.ports.reduce((n,p)=>n+p.rxMbps,0),tx=sw.ports.reduce((n,p)=>n+p.txMbps,0);return <section className="inspector"><div className="switchhead"><span className={`state ${sw.status}`}/><div><h2>{sw.name}</h2><p>{sw.model} · {sw.address}</p></div></div><div className="gauges"><Metric value={`${sw.cpuPercent.toFixed(0)}%`} label="CPU"/><Metric value={sw.temperatureC?`${sw.temperatureC.toFixed(0)}°`:'–'} label="Temperatur"/><Metric value={sw.ports.filter(p=>p.link).length} label="Links"/></div><dl className="facts"><dt>Firmware</dt><dd>{sw.firmwareVersion||'–'}</dd><dt>Hardware</dt><dd>{sw.hardwareVersion||'–'}</dd><dt>PoE Budget</dt><dd>{sw.poeBudgetWatts?`${sw.poeUsageWatts.toFixed(1)} / ${sw.poeBudgetWatts.toFixed(0)} W`:'–'}</dd></dl><h3>Ports</h3><div className="portgrid">{sw.ports.map(p=><div className={`port ${p.link?'up':''}`} key={p.index} title={`${p.name}: RX ${p.rxMbps.toFixed(3)} / TX ${p.txMbps.toFixed(3)} Mbit/s · ${p.errors} Fehler`}><b>{p.index}</b><i style={p.link?{background:roles[p.role]??roles.Unassigned}:{}}/><small>{p.link?p.role:'frei'}</small></div>)}</div><div className="traffic"><b>Live Traffic</b><span>RX {rx.toFixed(3)} Mbit/s</span><span>TX {tx.toFixed(3)} Mbit/s</span></div><button className="primary" onClick={onEditVLANs}>VLANs und Ports bearbeiten</button></section>}
function Role({role}:{role:string}){return <span className="role"><i style={{background:roles[role]??roles.Unassigned}}/>{role}</span>}
function Health({title,ok,text}:{title:string;ok:boolean;text:string}){return <section className="health-card"><span className={ok?'ok':'pending'}>{ok?'✓':'!'}</span><div><b>{title}</b><p>{text}</p></div></section>}
function DataPanel({children}:{children:React.ReactNode}){return <div className="data-panel">{children}</div>}
function Loading(){return <div className="loading">Daten werden geladen …</div>}
function Empty({text}:{text:string}){return <tr><td colSpan={8} className="empty">{text}</td></tr>}
